{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.fullname" . }}-secrets
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  anon-key: {{ .Values.secrets.anonKey | b64enc | quote }}
  service-role-key: {{ .Values.secrets.serviceRoleKey | b64enc | quote }}
  dashboard-username: {{ .Values.secrets.dashboardUsername | b64enc | quote }}
  dashboard-password: {{ .Values.secrets.dashboardPassword | b64enc | quote }}
  secret-key-base: {{ .Values.secrets.secretKeyBase | b64enc | quote }}
  vault-enc-key: {{ .Values.secrets.vaultEncKey | b64enc | quote }}
  logflare-public-access-token: {{ .Values.secrets.logflarePublicAccessToken | b64enc | quote }}
  logflare-private-access-token: {{ .Values.secrets.logflarePrivateAccessToken | b64enc | quote }}
  s3-access-key: {{ .Values.secrets.s3AccessKey | b64enc | quote }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
{{- end }}
