apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-db-pvc
  labels:
    app: supabase
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi