apiVersion: v1
kind: Service
metadata:
  name: supabase-db
  labels:
    app: supabase
    component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: supabase
    component: database 