# 定义加密规则
# 使用前需要设置环境变量：
# Windows PowerShell:
#   $env:SOPS_AGE_KEY_FILE = "C:\path\to\your\key.txt"
# Linux/Mac:
#   export SOPS_AGE_KEY_FILE="/path/to/your/key.txt"
#
# 示例：
#   $env:SOPS_AGE_KEY_FILE = "C:\Users\YourUsername\key.txt"
#   或
#   export SOPS_AGE_KEY_FILE="$HOME/key.txt"

creation_rules:
  # 匹配所有以 .secret.yaml/.secret.yml 或 .secret.sops.yaml/.secret.sops.yml 结尾的文件
  - path_regex: .*\.secret(\.sops)?\.(yaml|yml)
    key_groups:
      # 使用 age 加密方式
      # 方括号内是 age 公钥，用于加密文件
      # 只有持有对应私钥的人才能解密这些文件
      - age: ["age1u04cak8ww8et2r3nwv0rey6c2rr3r5c9cahtr8mapazsrqlpuf2s9zwyae"]
