apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-storage-config
  labels:
    app: supabase-storage
    component: storage
data:
  # Storage API configuration
  POSTGREST_URL: "http://supabase-rest:3000"
  FILE_SIZE_LIMIT: "52428800"
  STORAGE_BACKEND: "file"
  FILE_STORAGE_BACKEND_PATH: "/var/lib/storage"
  TENANT_ID: "stub"
  REGION: "stub"
  GLOBAL_S3_BUCKET: "stub"
  ENABLE_IMAGE_TRANSFORMATION: "true"
  IMGPROXY_URL: "http://supabase-imgproxy:5001"
