apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-storage
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  replicas: {{ .Values.storage.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: storage
    spec:
      containers:
      - name: storage
        image: {{ .Values.storage.image.repository }}:{{ .Values.storage.image.tag }}
        imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: ANON_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: anon-key
        - name: SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: service-role-key
        - name: POSTGREST_URL
          value: "http://{{ include "supabase.fullname" . }}-rest:3000"
        - name: PGRST_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: jwt-secret
        - name: DATABASE_URL
          value: "postgres://supabase_storage_admin:$(POSTGRES_PASSWORD)@{{ include "supabase.fullname" . }}-db:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
        - name: FILE_SIZE_LIMIT
          value: {{ .Values.storage.fileSizeLimit | quote }}
        - name: STORAGE_BACKEND
          value: {{ .Values.storage.backend | quote }}
        - name: FILE_STORAGE_BACKEND_PATH
          value: "/var/lib/storage"
        - name: TENANT_ID
          value: "stub"
        - name: REGION
          value: "stub"
        - name: GLOBAL_S3_BUCKET
          value: "stub"
        - name: ENABLE_IMAGE_TRANSFORMATION
          value: "true"
        - name: IMGPROXY_URL
          value: "http://{{ include "supabase.fullname" . }}-imgproxy:5001"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: postgres-password
        {{- if eq .Values.storage.backend "s3" }}
        - name: GLOBAL_S3_BUCKET
          value: {{ .Values.storage.s3.bucket | quote }}
        - name: GLOBAL_S3_ENDPOINT
          value: {{ .Values.storage.s3.endpoint | quote }}
        - name: GLOBAL_S3_PROTOCOL
          value: {{ .Values.storage.s3.protocol | quote }}
        - name: GLOBAL_S3_FORCE_PATH_STYLE
          value: {{ .Values.storage.s3.forcePathStyle | quote }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: s3-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: s3-secret-key
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.storage.s3.defaultRegion | quote }}
        {{- end }}
        {{- with .Values.storage.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: storage-data
          mountPath: /var/lib/storage
        {{- with .Values.storage.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.storage.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.storage.resources | nindent 10 }}
      volumes:
      - name: storage-data
        {{- if .Values.storage.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "supabase.fullname" . }}-storage-pvc
        {{- else }}
        emptyDir: {}
        {{- end }} 