{{- if and .Values.storage.enabled .Values.storage.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.fullname" . }}-storage-pvc
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.storage.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size | quote }}
  {{- if .Values.storage.persistence.storageClass }}
  storageClassName: {{ .Values.storage.persistence.storageClass | quote }}
  {{- end }}
{{- end }} 