apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.podLabels }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.deployment.containers.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.containers.port }}
  selector:
    app: {{ .Values.podLabels }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}