apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
  labels:
    app: supabase-studio
    component: studio
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: supabase-studio
    component: studio
