apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-auth
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redisPassword | b64enc | quote }}