namespace: test-namespace

service:
  name: nginx-service
  type: NodePort

deployment:
  name: nginx-deployment
  replicas: 2
  image: nginx
  tag: 1.17.0
  containers:
    name: nginx-container
    port: 80

podLabels: nginx