apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-kong
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: kong
spec:
  replicas: {{ .Values.kong.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kong
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kong
    spec:
      containers:
      - name: kong
        image: {{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}
        imagePullPolicy: {{ .Values.kong.image.pullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8443
          name: https
        env:
        {{- $defaultEnv := list }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "KONG_DATABASE" "value" "off") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "KONG_DECLARATIVE_CONFIG" "value" "/home/kong/kong.yml") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "KONG_DNS_ORDER" "value" "LAST,A,CNAME") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "KONG_PLUGINS" "value" "request-transformer,cors,key-auth,acl,basic-auth") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "KONG_NGINX_PROXY_PROXY_BUFFER_SIZE" "value" "160k") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "KONG_NGINX_PROXY_PROXY_BUFFERS" "value" "64 160k") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "SUPABASE_ANON_KEY" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "anon-key"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "SUPABASE_SERVICE_KEY" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "service-role-key"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "DASHBOARD_USERNAME" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "dashboard-username"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "DASHBOARD_PASSWORD" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "dashboard-password"))) }}
        {{- include "supabase.envVars" (dict "env" $defaultEnv "overrides" .Values.kong.envOverrides) | nindent 8 }}
        {{- with .Values.kong.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: kong-config
          mountPath: /home/kong/temp.yml
          subPath: kong.yml
        resources:
          {{- toYaml .Values.kong.resources | nindent 10 }}
      volumes:
      - name: kong-config
        configMap:
          name: {{ include "supabase.fullname" . }}-kong-config 