apiVersion: v1
kind: Service
metadata:
  name: supabase-kong
  labels:
    app: supabase-kong
    component: kong
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: supabase-kong
    component: kong
