apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  selector:
  {{- toYaml .Values.ingress.selector | nindent 4 }}
  type: {{ .Values.ingress.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
