apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-vector
  labels:
    app: supabase-vector
    component: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-vector
      component: vector
  template:
    metadata:
      labels:
        app: supabase-vector
        component: vector
    spec:
      containers:
        - name: vector
          image: timberio/vector:0.28.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          
          # Load environment variables from Secret
          envFrom:
            - secretRef:
                name: supabase-vector-secret
          
          # Mount vector configuration
          volumeMounts:
            - name: vector-config
              mountPath: /etc/vector
              readOnly: true
            # Mount Docker socket for log collection (在 Kubernetes 中通常不推荐，但为了兼容性)
            # 注意：这需要特殊的安全配置
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: true
          
          # 启动命令
          args: ["--config", "/etc/vector/vector.yml"]
          
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: 9001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          
          # Security context
          securityContext:
            # 需要特权访问 Docker socket
            privileged: true
      
      volumes:
        - name: vector-config
          configMap:
            name: supabase-vector-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      
      # 由于需要访问 Docker socket，需要特殊的安全配置
      securityContext:
        runAsUser: 0  # 以 root 用户运行以访问 Docker socket
      
      # 节点选择器和容忍度（可选）
      nodeSelector: {}
      tolerations: []
      affinity: {}
