apiVersion: v1
kind: Service
metadata:
  name: supabase-vector
  labels:
    app: supabase-vector
    component: vector
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    app: supabase-vector
    component: vector
