apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-imgproxy-storage
  labels:
    app: supabase-imgproxy
    component: imgproxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and modify if you need a specific storage class
  # storageClassName: your-storage-class
