apiVersion: v1
kind: Service
metadata:
  name: supabase-imgproxy
  labels:
    app: supabase-imgproxy
    component: imgproxy
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    app: supabase-imgproxy
    component: imgproxy
