{{- if .Values.imgproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-imgproxy
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: imgproxy
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "supabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: imgproxy
{{- end }} 