{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-db
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      {{- with .Values.database.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init-db
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        command:
        - sh
        - -c
        - |
          if [ ! -f /var/lib/postgresql/data/PG_VERSION ]; then
            echo "Initializing database..."
            mkdir -p /var/lib/postgresql/data
            chown -R 999:999 /var/lib/postgresql/data
            chmod 700 /var/lib/postgresql/data
          else
            echo "Database already initialized, fixing permissions..."
            chown -R 999:999 /var/lib/postgresql/data
            chmod 700 /var/lib/postgresql/data
          fi
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
      - name: postgres
        image: {{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}
        imagePullPolicy: {{ .Values.database.image.pullPolicy }}
        {{- with .Values.database.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.database.postgres.port }}
          name: postgresql
        env:
        - name: POSTGRES_HOST
          value: "/var/run/postgresql"
        - name: POSTGRES_PORT
          value: {{ .Values.database.postgres.port | quote }}
        - name: PGPORT
          value: {{ .Values.database.postgres.port | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.postgres.database | quote }}
        - name: PGDATABASE
          value: {{ .Values.database.postgres.database | quote }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.secretName" . }}
              key: jwt-secret
        - name: JWT_EXP
          value: {{ .Values.database.jwtExpiry | quote }}
        {{- with .Values.database.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        command:
        - "postgres"
        - "-c"
        - "config_file=/etc/postgresql/postgresql.conf"
        - "-c"
        - "log_min_messages=fatal"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
            - -h
            - localhost
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.database.resources | nindent 10 }}
      volumes:
      - name: postgres-data
        {{- if .Values.database.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "supabase.fullname" . }}-db-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: postgres-config
        configMap:
          name: {{ include "supabase.fullname" . }}-postgres-config
      - name: init-scripts
        configMap:
          name: {{ include "supabase.fullname" . }}-init-scripts
{{- end }} 