{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "ib-gateway-docker.fullname" .) }}
  labels:
    {{- include "ib-gateway-docker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.twsUserid }}
  TWS_USERID: {{ .Values.secret.twsUserid | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.twsPassword }}
  TWS_PASSWORD: {{ .Values.secret.twsPassword | b64enc | quote }}
  {{- end }}
  VNC_SERVER_PASSWORD: {{ .Values.secret.vncPassword | default "" | b64enc | quote }}
{{- end }} 