apiVersion: v1
kind: Service
metadata:
  name: {{ include "ib-gateway-docker.fullname" . }}
  labels:
    {{- include "ib-gateway-docker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    {{- if $port.enabled }}
    - name: {{ $name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "ib-gateway-docker.selectorLabels" . | nindent 4 }}
