apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-realtime-config
  labels:
    app: supabase-realtime
    component: realtime
data:
  # Realtime configuration
  PORT: "4000"
  DB_HOST: "supabase-db"
  DB_PORT: "5432"
  DB_USER: "supabase_admin"
  DB_NAME: "postgres"
  DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
  DB_ENC_KEY: "supabaserealtime"
  ERL_AFLAGS: "-proto_dist inet_tcp"
  DNS_NODES: "''"
  RLIMIT_NOFILE: "10000"
  APP_NAME: "realtime"
  SEED_SELF_HOST: "true"
  RUN_JANITOR: "true"
