apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-realtime
  labels:
    app: supabase-realtime
    component: realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-realtime
      component: realtime
  template:
    metadata:
      labels:
        app: supabase-realtime
        component: realtime
    spec:
      # Add init container to wait for dependencies
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for database to be ready..."
              until nc -z supabase-db 5432; do
                echo "Database not ready, waiting..."
                sleep 2
              done
              echo "Database is ready!"
        - name: wait-for-analytics
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for analytics to be ready..."
              until nc -z supabase-analytics 4000; do
                echo "Analytics not ready, waiting..."
                sleep 2
              done
              echo "Analytics is ready!"
      containers:
        - name: realtime
          # Note: container name in Docker Compose is realtime-dev.supabase-realtime
          # This is because realtime constructs tenant id by parsing the subdomain
          image: supabase/realtime:v2.34.47
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          
          # Load environment variables from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: supabase-realtime-config
            - secretRef:
                name: supabase-realtime-secret

          # Health checks based on the Docker Compose configuration
          # Note: Using TCP probe instead of HTTP due to auth requirements
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

      restartPolicy: Always
