apiVersion: v1
kind: Service
metadata:
  name: supabase-realtime
  labels:
    app: supabase-realtime
    component: realtime
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: supabase-realtime
    component: realtime
