apiVersion: v1
kind: Service
metadata:
  name: supabase-analytics
  labels:
    app: supabase
    component: analytics
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: supabase
    component: analytics 