{{- if .Values.pooler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-pooler
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: pooler
spec:
  replicas: {{ .Values.pooler.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pooler
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pooler
    spec:
      containers:
      - name: pooler
        image: {{ .Values.pooler.image.repository }}:{{ .Values.pooler.image.tag }}
        imagePullPolicy: {{ .Values.pooler.image.pullPolicy }}
        ports:
        - containerPort: 6543
          name: proxy
        - containerPort: 5432
          name: postgresql
        env:
        {{- $defaultEnv := list }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PORT" "value" "4000") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POSTGRES_PORT" "value" (.Values.database.postgres.port | quote)) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POSTGRES_DB" "value" .Values.database.postgres.database) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POSTGRES_PASSWORD" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "postgres-password"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "DATABASE_URL" "value" (printf "ecto://supabase_admin:%s@%s-db:%s/_supabase" (.Values.secrets.postgresPassword | quote) (include "supabase.fullname" .) (.Values.database.postgres.port | quote))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "CLUSTER_POSTGRES" "value" "true") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "SECRET_KEY_BASE" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "secret-key-base"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "VAULT_ENC_KEY" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "vault-enc-key"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "API_JWT_SECRET" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "jwt-secret"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "METRICS_JWT_SECRET" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "jwt-secret"))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "REGION" "value" "local") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "ERL_AFLAGS" "value" "-proto_dist inet_tcp") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POOLER_TENANT_ID" "value" .Values.pooler.tenantId) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POOLER_DEFAULT_POOL_SIZE" "value" .Values.pooler.defaultPoolSize) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POOLER_MAX_CLIENT_CONN" "value" .Values.pooler.maxClientConn) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "POOLER_POOL_MODE" "value" "transaction") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "DB_POOL_SIZE" "value" .Values.pooler.dbPoolSize) }}
        {{- include "supabase.envVars" (dict "env" $defaultEnv "overrides" .Values.pooler.envOverrides) | nindent 8 }}
        {{- with .Values.pooler.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.pooler.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.pooler.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.pooler.resources | nindent 10 }}
      volumes:
      - name: pooler-config
        configMap:
          name: {{ include "supabase.fullname" . }}-pooler-config 
{{- end }} 