apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase.fullname" . }}-pooler
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: pooler
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.postgres.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
    - port: {{ .Values.pooler.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "supabase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pooler 