apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-rest
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: rest
spec:
  replicas: {{ .Values.rest.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rest
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rest
    spec:
      containers:
      - name: rest
        image: {{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag }}
        imagePullPolicy: {{ .Values.rest.image.pullPolicy }}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PGRST_DB_URI
          value: "postgres://authenticator:$(POSTGRES_PASSWORD)@{{ include "supabase.fullname" . }}-db:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"
        - name: PGRST_DB_SCHEMAS
          value: {{ .Values.rest.dbSchemas | quote }}
        - name: PGRST_DB_ANON_ROLE
          value: "anon"
        - name: PGRST_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: jwt-secret
        - name: PGRST_DB_USE_LEGACY_GUCS
          value: "false"
        - name: PGRST_APP_SETTINGS_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: jwt-secret
        - name: PGRST_APP_SETTINGS_JWT_EXP
          value: {{ .Values.rest.jwtExpiry | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: postgres-password
        {{- with .Values.rest.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        command:
        - "postgrest"
        resources:
          {{- toYaml .Values.rest.resources | nindent 10 }} 