apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
  labels:
    app: supabase-rest
    component: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-rest
      component: rest
  template:
    metadata:
      labels:
        app: supabase-rest
        component: rest
    spec:
      # Add init container to wait for dependencies
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for database to be ready..."
              until nc -z supabase-db 5432; do
                echo "Database not ready, waiting..."
                sleep 2
              done
              echo "Database is ready!"
        - name: wait-for-analytics
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for analytics to be ready..."
              until nc -z supabase-analytics 4000; do
                echo "Analytics not ready, waiting..."
                sleep 2
              done
              echo "Analytics is ready!"
      containers:
        - name: rest
          image: postgrest/postgrest:v12.2.12
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          
          # Load environment variables from ConfigMap and Secret
          envFrom:
            - configMapRef:
                name: supabase-rest-config
            - secretRef:
                name: supabase-rest-secret

          # Command from Docker Compose
          command: ["postgrest"]

          # Health checks
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

      restartPolicy: Always
