apiVersion: v1
kind: Secret
metadata:
  name: supabase-rest-secret
  labels:
    app: supabase-rest
    component: rest
type: Opaque
data:
  # Base64 encoded values - using authenticator user for PostgREST
  PGRST_DB_URI: "cG9zdGdyZXM6Ly9hdXRoZW50aWNhdG9yOnlvdXItc3VwZXItc2VjcmV0LWFuZC1sb25nLXBvc3RncmVzLXBhc3N3b3JkQHN1cGFiYXNlLWRiOjU0MzIvcG9zdGdyZXM="
  PGRST_JWT_SECRET: "eW91ci1zdXBlci1zZWNyZXQtand0LXRva2VuLXdpdGgtYXQtbGVhc3QtMzItY2hhcmFjdGVycy1sb25n"
  PGRST_APP_SETTINGS_JWT_SECRET: "eW91ci1zdXBlci1zZWNyZXQtand0LXRva2VuLXdpdGgtYXQtbGVhc3QtMzItY2hhcmFjdGVycy1sb25n"
  PGRST_APP_SETTINGS_JWT_EXP: "MzYwMA=="
