apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  labels:
    app: supabase-rest
    component: rest
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: supabase-rest
    component: rest
