{{- if .Values.meta.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-meta
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
spec:
  replicas: {{ .Values.meta.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: meta
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: meta
    spec:
      containers:
      - name: meta
        image: {{ .Values.meta.image.repository }}:{{ .Values.meta.image.tag }}
        imagePullPolicy: {{ .Values.meta.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        {{- $defaultEnv := list }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PG_META_PORT" "value" "8080") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PG_META_DB_HOST" "value" (printf "%s-db" (include "supabase.fullname" .))) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PG_META_DB_PORT" "value" (.Values.database.postgres.port | quote)) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PG_META_DB_NAME" "value" .Values.database.postgres.database) }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PG_META_DB_USER" "value" "supabase_admin") }}
        {{- $defaultEnv = append $defaultEnv (dict "name" "PG_META_DB_PASSWORD" "valueFrom" (dict "secretKeyRef" (dict "name" (include "supabase.secretName" .) "key" "postgres-password"))) }}
        {{- include "supabase.envVars" (dict "env" $defaultEnv "overrides" .Values.meta.envOverrides) | nindent 8 }}
        {{- with .Values.meta.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.meta.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.meta.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.meta.resources | nindent 10 }}
{{- end }} 