apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.fullname" . }}-meta
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
    app.kubernetes.io/component: meta
spec:
  replicas: {{ .Values.meta.replicaCount }}
  selector:
    matchLabels:
      {{- include "supabase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: meta
  template:
    metadata:
      labels:
        {{- include "supabase.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: meta
    spec:
      containers:
      - name: meta
        image: {{ .Values.meta.image.repository }}:{{ .Values.meta.image.tag }}
        imagePullPolicy: {{ .Values.meta.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PG_META_PORT
          value: "8080"
        - name: PG_META_DB_HOST
          value: "{{ include "supabase.fullname" . }}-db"
        - name: PG_META_DB_PORT
          value: {{ .Values.postgres.port | quote }}
        - name: PG_META_DB_NAME
          value: {{ .Values.postgres.database | quote }}
        - name: PG_META_DB_USER
          value: "supabase_admin"
        - name: PG_META_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.fullname" . }}-secrets
              key: postgres-password
        {{- with .Values.meta.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.meta.resources | nindent 10 }} 